version: "3.9"

services:
  food-filter-app:
    container_name: food-filter-app
    build:
      context: ./FoodFilter
      dockerfile: ./Dockerfile
    ports:
      # external:internal
      - "8000:80"
    depends_on:
      - food-filter-db
    environment:
      - ConnectionStrings:DefaultConnection=Host=food-filter-db:5432;Database=food-filter;Username=postgres;Password=postgres
  
  
  food-filter-db:
    container_name: food-filter-db
    image: "postgres:15.2-bullseye"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      # external:internal
      - "5446:5432"
    volumes:
      - food-filter-db-postgres-volume:\Users\danyi\RiderProjects\postgresql

volumes:
  food-filter-db-postgres-volume:
 